[2022-11-18 11:41:00,996]: Skip avahi_enable search...
[2022-11-18 11:41:00,997]: SSL is not enabled...
[2022-11-18 11:41:00,999]: [-> CONNECT           ] Connect to Host: 127.0.0.1:11083
[2022-11-18 11:41:01,001]: Some error
[2022-11-18 11:41:01,002]: Traceback message : Traceback (most recent call last):
  File "/home/jyeom/anaconda3/envs/py37tf26/lib/python3.7/site-packages/big_thing_py/manager_thing.py", line 208, in scan_staff_message
    msg = self._receive_staff_packet()
  File "/home/jyeom/big-thing-py-examples/manager_thing/lora_manager_thing/lora_manager_thing.py", line 99, in _receive_staff_packet
    if self.verify_lora_request_result(lora_device_list):
UnboundLocalError: local variable 'lora_device_list' referenced before assignment

Error: local variable 'lora_device_list' referenced before assignment
[2022-11-18 11:41:01,002]: Traceback message : Traceback (most recent call last):
  File "/home/jyeom/anaconda3/envs/py37tf26/lib/python3.7/site-packages/big_thing_py/manager_thing.py", line 157, in run
    raise Exception('_g_exit was set!!!')
Exception: _g_exit was set!!!

Error: _g_exit was set!!!
[2022-11-18 11:41:03,005]: Traceback message : Traceback (most recent call last):
  File "/home/jyeom/anaconda3/envs/py37tf26/lib/python3.7/site-packages/big_thing_py/manager_thing.py", line 183, in wrapup
    thread.exit()
AttributeError: 'SoPThread' object has no attribute 'exit'

Error: 'SoPThread' object has no attribute 'exit'
