[2022-11-18 13:28:21,793]: Skip avahi_enable search...
[2022-11-18 13:28:21,793]: SSL is not enabled...
[2022-11-18 13:28:21,796]: [-> CONNECT           ] Connect to Host: 127.0.0.1:11083
[2022-11-18 13:28:21,798]: Some error
[2022-11-18 13:28:21,799]: Traceback message : Traceback (most recent call last):
  File "/home/jyeom/anaconda3/envs/py37tf26/lib/python3.7/site-packages/big_thing_py/manager_thing.py", line 228, in receive_staff_message_thread_func
    self._handle_staff_message(msg)
  File "/home/jyeom/big-thing-py-examples/manager_thing/lora_manager_thing/lora_manager_thing.py", line 34, in _handle_staff_message
    for idx, lora_device in lora_device_list.items():
AttributeError: 'dict_keys' object has no attribute 'items'

Error: 'dict_keys' object has no attribute 'items'
[2022-11-18 13:28:21,799]: Traceback message : Traceback (most recent call last):
  File "/home/jyeom/anaconda3/envs/py37tf26/lib/python3.7/site-packages/big_thing_py/manager_thing.py", line 157, in run
    raise Exception('_g_exit was set!!!')
Exception: _g_exit was set!!!

Error: _g_exit was set!!!
[2022-11-18 13:28:23,800]: Traceback message : Traceback (most recent call last):
  File "/home/jyeom/anaconda3/envs/py37tf26/lib/python3.7/site-packages/big_thing_py/manager_thing.py", line 183, in wrapup
    thread.exit()
AttributeError: 'SoPThread' object has no attribute 'exit'

Error: 'SoPThread' object has no attribute 'exit'
